if(NOT DEFINED MPI_FOUND)
    find_package(MPI)
endif()
find_library(HYPRE_LIBRARIES HYPRE)
find_path(HYPRE_INCLUDE_DIRS HYPRE.h PATH_SUFFIXES hypre)

if(HYPRE_LIBRARIES AND HYPRE_INCLUDE_DIRS)
    add_library(HYPRE::HYPRE UNKNOWN IMPORTED)
    set_target_properties(HYPRE::HYPRE PROPERTIES
        IMPORTED_LOCATION ${HYPRE_LIBRARIES}
        INTERFACE_INCLUDE_DIRECTORIES ${HYPRE_INCLUDE_DIRS}
        INTERFACE_LINK_LIBRARIES $<$<BOOL:${MPI_FOUND}>:MPI::MPI_CXX>
    )
    try_run(_HYPRE_VERSION_RUN_RESULT _HYPRE_VERSION_COMPILE_RESULT
        "${CMAKE_CURRENT_BINARY_DIR}"
        "${CMAKE_CURRENT_LIST_DIR}/get_hypre_version.cpp"
        LINK_LIBRARIES HYPRE::HYPRE
        RUN_OUTPUT_VARIABLE HYPRE_VERSION
    )
    set(HYPRE_VERSION ${HYPRE_VERSION} CACHE STRING "HYPRE version")
    find_package_handle_standard_args(HYPRE
        REQUIRED_VARS HYPRE_LIBRARIES HYPRE_INCLUDE_DIRS
        VERSION_VAR HYPRE_VERSION
    )
endif()
